### ISSUE TITLE
Too many "Web3 connection attempt"s

### ISSUE THREAD

**Issue by jzencore** [cubedro/eth-net-intelligence-api#109]
On Mac OS X 10.9.5, when the geth --rpc instance gets in a funk, freezes, or fails to respond, pm2 node-app process error logs "[eth] =x= Web3 connection attempt #NNN failed" at the rate of 60 records per minute, various SyntaxErrors scattered throughout the log, along with the spawning of countless "(node)" processes, ultimately exhausting all of the system resources.   Perhaps some sort of additional connection rate limiting is needed in lib/node.js Node.prototype.checkWeb3Connection = function()?  Or how to keep node process forking under better control when there are connection errors?

**Comment by cubedro** [comment]
Added 500ms delay in 4df1573d46291eb98466d89f2fe88e9572415516
