### ISSUE TITLE
How do you connect to a local eth-netstats node?

### ISSUE THREAD

**Issue by a-jamesregan** [cubedro/eth-net-intelligence-api#216]
Could you please provide instructions on how to connect to a local eth-netstats node?  I have the node running just fine, but I don't see how to connect to it, I tried setting WS_SERVER to "wss://localhost:3000" but nothing happens.  And on the eth-netstats server, how do I set the port + secret + etc?  On the documentation, it reads "For full install instructions please read [the wiki][1]."  But the wiki has no information about how to run your own node.

[1]:https://github.com/ethereum/wiki/wiki/Network-Status

**Comment by cubedro** [comment]
WS_SERVER should be "ws://localhost:3000", the second "s" stands for secure.
For the server you have to pass WS_SERVER and PORT as environment variables.
