### ISSUE TITLE
clarify README against Ethereum wiki

### ISSUE THREAD

**Issue by ethers** [cubedro/eth-net-intelligence-api#88]
It is not clear whether the primary instructions are the Ethereum wiki
https://github.com/ethereum/wiki/wiki/Network-Status or this project's README.  Some editing, clarification, possible de-duplication, would be helpful.

**Comment by cubedro** [comment]
The README.md from this repo is the [Auto Installation on a fresh Ubuntu install](https://github.com/ethereum/wiki/wiki/Network-Status#auto-installation-on-a-fresh-ubuntu-install) section (2nd section) of the wiki page. These instructions will install and update everything you need (nodejs, npm, eth/geth, eth-net-intelligence-api) and will run both eth/geth and eth-net-intelligence-api.

The first part of the wiki page explains how to install, configure and run only eth-net-intelligence-api on OS X or Linux if you already have ethereum installed.
